### ISSUE TITLE
Renaming the class BenguardLogger

### ISSUE THREAD

**Issue by bienjaroslav** [Pscheidl/FortEE#10]
suggesting to rename the class [`BenguardLogger`](https://github.com/Pscheidl/FortEE/blob/master/src/main/java/cz/pscheidl/fortee/logging/BenguardLogger.java) to `FortLogger` (or `ForteeLogger`).

**Comment by Pscheidl** [comment]
Fixed. Build checked. Merged into master. Original branch deleted.
